"""empty message

Revision ID: 344299e3cbfc
Revises: 72e3a7ed55d4
Create Date: 2023-09-02 17:58:19.036197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '344299e3cbfc'
down_revision = '72e3a7ed55d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('calculated_rating',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('calculated_rating',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
