"""empty message

Revision ID: 5f38a08b8de2
Revises: c7a6f52f78f4
Create Date: 2023-09-29 10:50:05.445139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f38a08b8de2'
down_revision = 'c7a6f52f78f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('calculated_rating',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)

    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.drop_constraint('volunteer_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.create_unique_constraint('volunteer_email_key', ['email'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('calculated_rating',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
