"""empty message

Revision ID: 933c03a32617
Revises: 34a2696dfa10
Create Date: 2023-08-28 18:49:57.915073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '933c03a32617'
down_revision = '34a2696dfa10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('animal_shelter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=80), nullable=True))

    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=80), nullable=True))
        batch_op.drop_constraint('volunteer_city_key', type_='unique')
        batch_op.drop_constraint('volunteer_description_key', type_='unique')
        batch_op.drop_constraint('volunteer_zip_code_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.create_unique_constraint('volunteer_zip_code_key', ['zip_code'])
        batch_op.create_unique_constraint('volunteer_description_key', ['description'])
        batch_op.create_unique_constraint('volunteer_city_key', ['city'])
        batch_op.drop_column('address')

    with op.batch_alter_table('animal_shelter', schema=None) as batch_op:
        batch_op.drop_column('address')

    op.drop_table('report')
    op.drop_table('rating')
    # ### end Alembic commands ###
