"""empty message

Revision ID: 941264a72f10
Revises: 08a8b827c3b2
Create Date: 2023-08-28 18:24:52.067418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941264a72f10'
down_revision = '08a8b827c3b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_shelter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('cip_code', sa.String(length=10), nullable=False),
    sa.Column('cif', sa.String(length=20), nullable=False),
    sa.Column('web', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cif'),
    sa.UniqueConstraint('cip_code'),
    sa.UniqueConstraint('city'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('web')
    )
    op.create_table('volunteer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('cip_code', sa.String(length=10), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cip_code'),
    sa.UniqueConstraint('city'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volunteer')
    op.drop_table('animal_shelter')
    # ### end Alembic commands ###
