"""empty message

Revision ID: abc8feaac0bb
Revises: df54105e2aef
Create Date: 2023-08-28 18:32:04.636004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc8feaac0bb'
down_revision = 'df54105e2aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal_shelter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zip_code', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('animal_shelter_cip_code_key', type_='unique')
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.create_unique_constraint(None, ['zip_code'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('cip_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal_shelter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cip_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('animal_shelter_cip_code_key', ['cip_code'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('zip_code')

    # ### end Alembic commands ###
